# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'new_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(632, 406)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(10, 10, 611, 381))
        self.frame.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.app_name_label = QtWidgets.QLabel(self.frame)
        self.app_name_label.setGeometry(QtCore.QRect(170, 40, 291, 81))
        self.app_name_label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 36pt \"Bahnschrift SemiLight\";\n"
"")
        self.app_name_label.setObjectName("app_name_label")
        self.login_form = QtWidgets.QTextEdit(self.frame)
        self.login_form.setGeometry(QtCore.QRect(170, 190, 281, 31))
        self.login_form.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.login_form.setObjectName("login_form")
        self.password_form = QtWidgets.QTextEdit(self.frame)
        self.password_form.setGeometry(QtCore.QRect(170, 250, 281, 31))
        self.password_form.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.password_form.setObjectName("password_form")
        self.login_label = QtWidgets.QLabel(self.frame)
        self.login_label.setGeometry(QtCore.QRect(110, 190, 51, 31))
        self.login_label.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.login_label.setObjectName("login_label")
        self.password_label = QtWidgets.QLabel(self.frame)
        self.password_label.setGeometry(QtCore.QRect(80, 250, 81, 31))
        self.password_label.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.password_label.setObjectName("password_label")
        self.login_button = QtWidgets.QPushButton(self.frame)
        self.login_button.setGeometry(QtCore.QRect(250, 300, 111, 41))
        self.login_button.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 255, 255);\n"
"color: rgb(255, 170, 0);")
        self.login_button.setObjectName("login_button")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.app_name_label.setText(_translate("Dialog", "Form Autofill"))
        self.login_label.setText(_translate("Dialog", "Login"))
        self.password_label.setText(_translate("Dialog", "Password"))
        self.login_button.setText(_translate("Dialog", "Login"))
